[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "simtheory"
authors = [{name = "Chris Sharkey", email = "chris@simtheory.ai"}]
dynamic = ["version", "description"]
